/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["check_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user and organization */
        post: operations["register_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive JWT tokens */
        post: operations["login_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh an expired access token */
        post: operations["refresh_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API tokens for the current user */
        get: operations["list_api_tokens"];
        put?: never;
        /** Create a new API token */
        post: operations["create_api_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/api-tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API token */
        delete: operations["revoke_api_token"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations for the current user */
        get: operations["list_organizations"];
        put?: never;
        /** Create a new organization */
        post: operations["create_organization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization by ID */
        get: operations["get_organization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an organization */
        patch: operations["update_organization"];
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects for the current organization */
        get: operations["list_projects"];
        put?: never;
        /** Create a new project */
        post: operations["create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project by ID */
        get: operations["get_project"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["delete_project"];
        options?: never;
        head?: never;
        /** Update a project */
        patch: operations["update_project"];
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List instruments */
        get: operations["list_instruments"];
        put?: never;
        /** Register a new instrument */
        post: operations["create_instrument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an instrument by ID */
        get: operations["get_instrument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an instrument */
        patch: operations["update_instrument"];
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List desktop agents */
        get: operations["list_agents"];
        put?: never;
        /** Register a new desktop agent */
        post: operations["register_agent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a 6-digit pairing code for agent registration */
        post: operations["generate_pairing_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/pair/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll for pairing code approval (used by agent) */
        get: operations["poll_pairing_code"];
        put?: never;
        /** Approve a pairing code (user action in dashboard) */
        post: operations["approve_pairing_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a desktop agent by ID */
        get: operations["get_agent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a heartbeat from a desktop agent */
        post: operations["record_agent_heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List uploads for the current organization */
        get: operations["list_uploads"];
        put?: never;
        /** Upload an instrument data file */
        post: operations["upload_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an upload by ID */
        get: operations["get_upload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/reparse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger re-parsing of an upload */
        post: operations["reparse_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the raw uploaded file */
        get: operations["download_raw_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get parsed instrument data for an upload */
        get: operations["get_parsed_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/{upload_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chart-ready data for an upload (Plotly.js format) */
        get: operations["get_chart_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Full-text search across parsed instrument data */
        post: operations["search_data"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a data export job */
        post: operations["create_export"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List experiments */
        get: operations["list_experiments"];
        put?: never;
        /** Create a new experiment */
        post: operations["create_experiment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an experiment by ID */
        get: operations["get_experiment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an experiment (status transitions) */
        patch: operations["update_experiment"];
        trace?: never;
    };
    "/experiments/{experiment_id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record the outcome of an experiment */
        post: operations["record_experiment_outcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/link-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link an upload to an experiment */
        post: operations["link_upload_to_experiment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/link-upload/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink an upload from an experiment */
        delete: operations["unlink_upload_from_experiment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List campaigns */
        get: operations["list_campaigns"];
        put?: never;
        /** Create a new campaign */
        post: operations["create_campaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a campaign by ID */
        get: operations["get_campaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get campaign progress metrics */
        get: operations["get_campaign_progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhooks */
        get: operations["list_webhooks"];
        put?: never;
        /** Create a new webhook */
        post: operations["create_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a webhook by ID */
        get: operations["get_webhook"];
        put?: never;
        post?: never;
        /** Delete a webhook */
        delete: operations["delete_webhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit events */
        get: operations["list_audit_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get usage statistics */
        get: operations["get_usage_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sse/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subscribe to real-time SSE updates */
        get: operations["sse_updates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorDetail
         * @description Structured error detail with agent-actionable recovery hints
         */
        ErrorDetail: {
            /** @description Machine-readable error code */
            code: string;
            /** @description Human-readable error description */
            message: string;
            field?: string | null;
            suggestion?: string | null;
            /** @default false */
            retry: boolean;
            retry_after?: number | null;
        };
        /** PaginationMeta */
        PaginationMeta: {
            total_count: number;
            page: number;
            page_size: number;
            has_more: boolean;
        };
        /** ResponseMeta */
        ResponseMeta: {
            /** Format: uuid */
            request_id: string;
            /** Format: date-time */
            timestamp: string;
            pagination?: components["schemas"]["PaginationMeta"] | null;
        };
        /** TokenResponse */
        TokenResponse: {
            access_token: string;
            refresh_token: string;
            /** @default bearer */
            token_type: string;
            expires_in: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            full_name: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            full_name: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** ApiTokenCreate */
        ApiTokenCreate: {
            name: string;
            /**
             * @default read
             * @enum {string}
             */
            scope: "read" | "write" | "admin";
            /**
             * @default user
             * @enum {string}
             */
            identity_type: "user" | "agent";
            expires_at?: string | null;
        };
        /** ApiTokenResponse */
        ApiTokenResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            scope: string;
            identity_type: string;
            is_active: boolean;
            expires_at?: string | null;
            /** Format: date-time */
            created_at: string;
            token?: string | null;
        };
        /** OrganizationCreate */
        OrganizationCreate: {
            name: string;
            slug?: string;
        };
        /** OrganizationUpdate */
        OrganizationUpdate: {
            name?: string | null;
        };
        /** OrganizationResponse */
        OrganizationResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            plan: string;
            /** Format: date-time */
            created_at: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            name: string;
            description?: string | null;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            name?: string | null;
            description?: string | null;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** InstrumentCreate */
        InstrumentCreate: {
            name: string;
            /** @enum {string} */
            instrument_type: "spectrophotometer" | "plate_reader" | "hplc" | "pcr" | "balance";
            manufacturer?: string | null;
            model?: string | null;
            serial_number?: string | null;
            location?: string | null;
        };
        /** InstrumentUpdate */
        InstrumentUpdate: {
            name?: string | null;
            location?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** InstrumentResponse */
        InstrumentResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            instrument_type: "spectrophotometer" | "plate_reader" | "hplc" | "pcr" | "balance";
            manufacturer?: string | null;
            model?: string | null;
            serial_number?: string | null;
            location?: string | null;
            agent_id?: string | null;
            /** Format: date-time */
            created_at: string;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** AgentCreate */
        AgentCreate: {
            name: string;
            platform?: ("windows" | "macos" | "linux") | null;
        };
        /** AgentResponse */
        AgentResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            platform?: ("windows" | "macos" | "linux") | null;
            version?: string | null;
            /** @enum {string} */
            status: "active" | "inactive" | "offline";
            last_heartbeat_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** HeartbeatRequest */
        HeartbeatRequest: {
            version?: string | null;
            platform?: ("windows" | "macos" | "linux") | null;
            system_info?: {
                [key: string]: unknown;
            } | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Format: uuid */
            id: string;
            filename: string;
            content_hash: string;
            file_size_bytes: number;
            s3_key: string;
            mime_type?: string | null;
            /** @enum {string} */
            status: "uploaded" | "parsing" | "parsed" | "parse_failed" | "indexed";
            error_message?: string | null;
            instrument_type_detected?: string | null;
            parser_used?: string | null;
            /** Format: date-time */
            created_at: string;
            parsed_at?: string | null;
            indexed_at?: string | null;
            project_id?: string | null;
            instrument_id?: string | null;
        };
        /** ParsedDataResponse */
        ParsedDataResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            upload_id: string;
            instrument_type: string;
            parser_version: string;
            measurement_type?: string | null;
            sample_count?: number | null;
            data_summary: {
                [key: string]: unknown;
            };
            measurements: {
                [key: string]: unknown;
            }[];
            instrument_settings?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            created_at: string;
        };
        /** SearchRequest */
        SearchRequest: {
            query?: string | null;
            instrument_type?: string | null;
            measurement_type?: string | null;
            project_id?: string | null;
            date_from?: string | null;
            date_to?: string | null;
            /** @default 1 */
            page: number;
            /** @default 20 */
            page_size: number;
        };
        /** ExportCreateRequest */
        ExportCreateRequest: {
            /** @enum {string} */
            format: "csv" | "json" | "xlsx" | "pdf";
            /** @default [] */
            upload_ids: string[];
            /** @default {} */
            filters: {
                [key: string]: unknown;
            };
        };
        /** ExperimentCreate */
        ExperimentCreate: {
            intent: string;
            hypothesis?: string | null;
            parameters?: {
                [key: string]: unknown;
            } | null;
            campaign_id?: string | null;
            predecessor_ids?: string[] | null;
        };
        /** ExperimentUpdate */
        ExperimentUpdate: {
            status?: ("planned" | "running" | "completed" | "failed" | "cancelled") | null;
        };
        /** ExperimentResponse */
        ExperimentResponse: {
            /** Format: uuid */
            id: string;
            intent: string;
            hypothesis?: string | null;
            /** @enum {string} */
            status: "planned" | "running" | "completed" | "failed" | "cancelled";
            parameters?: {
                [key: string]: unknown;
            } | null;
            constraints?: {
                [key: string]: unknown;
            } | null;
            outcome?: {
                [key: string]: unknown;
            } | null;
            design_method?: string | null;
            campaign_id?: string | null;
            created_by?: string | null;
            /** Format: date-time */
            created_at: string;
            started_at?: string | null;
            completed_at?: string | null;
        };
        /** OutcomeRequest */
        OutcomeRequest: {
            results: {
                [key: string]: unknown;
            };
            success: boolean;
        };
        /** LinkUploadRequest */
        LinkUploadRequest: {
            /** Format: uuid */
            upload_id: string;
        };
        /** CampaignCreate */
        CampaignCreate: {
            name: string;
            description?: string | null;
            goal?: string | null;
            max_experiments?: number | null;
        };
        /** CampaignResponse */
        CampaignResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            goal?: string | null;
            status: string;
            experiment_count: number;
            max_experiments?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        /** WebhookCreate */
        WebhookCreate: {
            /** Format: uri */
            url: string;
            events: string[];
            secret?: string | null;
        };
        /** WebhookResponse */
        WebhookResponse: {
            /** Format: uuid */
            id: string;
            url: string;
            events: string[];
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Format: uuid */
            id: string;
            action: string;
            entity_type: string;
            entity_id?: string | null;
            actor_id?: string | null;
            actor_email?: string | null;
            diff?: {
                [key: string]: unknown;
            } | null;
            hash?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Envelope_ApiTokenResponse: {
            data?: components["schemas"]["ApiTokenResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_ApiTokenResponse: {
            data?: components["schemas"]["ApiTokenResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_OrganizationResponse: {
            data?: components["schemas"]["OrganizationResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_OrganizationResponse: {
            data?: components["schemas"]["OrganizationResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_ProjectResponse: {
            data?: components["schemas"]["ProjectResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_ProjectResponse: {
            data?: components["schemas"]["ProjectResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_InstrumentResponse: {
            data?: components["schemas"]["InstrumentResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_InstrumentResponse: {
            data?: components["schemas"]["InstrumentResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_AgentResponse: {
            data?: components["schemas"]["AgentResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_AgentResponse: {
            data?: components["schemas"]["AgentResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_UploadResponse: {
            data?: components["schemas"]["UploadResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_UploadResponse: {
            data?: components["schemas"]["UploadResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_ParsedDataResponse: {
            data?: components["schemas"]["ParsedDataResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_ParsedDataResponse: {
            data?: components["schemas"]["ParsedDataResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_ExperimentResponse: {
            data?: components["schemas"]["ExperimentResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_ExperimentResponse: {
            data?: components["schemas"]["ExperimentResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_CampaignResponse: {
            data?: components["schemas"]["CampaignResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_CampaignResponse: {
            data?: components["schemas"]["CampaignResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_WebhookResponse: {
            data?: components["schemas"]["WebhookResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_WebhookResponse: {
            data?: components["schemas"]["WebhookResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_AuditEventResponse: {
            data?: components["schemas"]["AuditEventResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_AuditEventResponse: {
            data?: components["schemas"]["AuditEventResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_TokenResponse: {
            data?: components["schemas"]["TokenResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_TokenResponse: {
            data?: components["schemas"]["TokenResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_UserResponse: {
            data?: components["schemas"]["UserResponse"] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_list_UserResponse: {
            data?: components["schemas"]["UserResponse"][] | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
        Envelope_dict: {
            data?: {
                [key: string]: unknown;
            } | null;
            meta: components["schemas"]["ResponseMeta"];
            errors: components["schemas"]["ErrorDetail"][];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope_dict"];
            };
        };
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope_dict"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope_dict"];
            };
        };
    };
    parameters: {
        /** @description Page number (1-indexed) */
        Page: number;
        /** @description Items per page */
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    check_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    register_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    login_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenResponse"];
                };
            };
        };
    };
    list_api_tokens: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ApiTokenResponse"];
                };
            };
        };
    };
    create_api_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiTokenCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ApiTokenResponse"];
                };
            };
        };
    };
    revoke_api_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    list_organizations: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_OrganizationResponse"];
                };
            };
        };
    };
    create_organization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OrganizationResponse"];
                };
            };
        };
    };
    get_organization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OrganizationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    update_organization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OrganizationResponse"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ProjectResponse"];
                };
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectResponse"];
                };
            };
        };
    };
    get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    delete_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    update_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectResponse"];
                };
            };
        };
    };
    list_instruments: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
                /** @description Filter by instrument type */
                instrument_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_InstrumentResponse"];
                };
            };
        };
    };
    create_instrument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InstrumentResponse"];
                };
            };
        };
    };
    get_instrument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InstrumentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    update_instrument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentUpdate"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InstrumentResponse"];
                };
            };
        };
    };
    list_agents: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_AgentResponse"];
                };
            };
        };
    };
    register_agent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    generate_pairing_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    poll_pairing_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 6-digit pairing code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    approve_pairing_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 6-digit pairing code */
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    get_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AgentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    record_agent_heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AgentResponse"];
                };
            };
        };
    };
    list_uploads: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
                /** @description Filter by status */
                status?: "uploaded" | "parsing" | "parsed" | "parse_failed" | "indexed";
                /** @description Filter by project */
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_UploadResponse"];
                };
            };
        };
    };
    upload_file: {
        parameters: {
            query?: {
                /** @description Associate with a project */
                project_id?: string;
                /** @description Associate with an instrument */
                instrument_id?: string;
                /** @description Allow duplicate uploads */
                allow_duplicate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Instrument data file
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UploadResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    get_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UploadResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    reparse_upload: {
        parameters: {
            query?: {
                /** @description Instrument type hint */
                instrument_type?: string;
            };
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UploadResponse"];
                };
            };
        };
    };
    download_raw_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw file content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    get_parsed_data: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ParsedDataResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    get_chart_data: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    search_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    create_export: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCreateRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    list_experiments: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
                /** @description Filter by status */
                status?: "planned" | "running" | "completed" | "failed" | "cancelled";
                /** @description Filter by campaign */
                campaign_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ExperimentResponse"];
                };
            };
        };
    };
    create_experiment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExperimentResponse"];
                };
            };
        };
    };
    get_experiment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExperimentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    update_experiment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentUpdate"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExperimentResponse"];
                };
            };
        };
    };
    record_experiment_outcome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExperimentResponse"];
                };
            };
        };
    };
    link_upload_to_experiment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkUploadRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    unlink_upload_from_experiment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    list_campaigns: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_CampaignResponse"];
                };
            };
        };
    };
    create_campaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CampaignResponse"];
                };
            };
        };
    };
    get_campaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CampaignResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    get_campaign_progress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    list_webhooks: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_WebhookResponse"];
                };
            };
        };
    };
    create_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_WebhookResponse"];
                };
            };
        };
    };
    get_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_WebhookResponse"];
                };
            };
        };
    };
    delete_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    list_audit_events: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                page_size?: components["parameters"]["PageSize"];
                /** @description Filter by entity type */
                entity_type?: string;
                /** @description Filter by entity ID */
                entity_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_AuditEventResponse"];
                };
            };
        };
    };
    get_usage_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict"];
                };
            };
        };
    };
    sse_updates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
